import type { AnalysisResult } from '../analyzer.js';
import { CONFIG_LANGUAGES } from '../detectors/languages.js';

/**
 * Generates a compact, structured context brief designed to be pasted at the
 * top of an LLM conversation to orient it about the codebase.
 *
 * Design goals:
 * - Concise: fits in ~300–600 tokens
 * - Structured: uses markdown headers and lists LLMs handle well
 * - Honest: explicitly says "heuristic" where it is
 * - Actionable: gives the LLM enough to help without dumping the entire repo
 */
export function renderForAi(result: AnalysisResult): string {
  const { name, frameworks, scripts, entryPoints, startHere, languages, tools, git } = result;
  const generated = new Date().toISOString().split('T')[0];

  const lines: string[] = [];

  lines.push(`# Codebase Context: ${name}`);
  lines.push(`> Generated by codeglance ${generated} — heuristic, not exhaustive`);
  lines.push('');

  // Type + stack
  lines.push('## Stack');
  if (frameworks.summary && frameworks.summary !== 'Unknown project type') {
    lines.push(`${frameworks.summary}`);
  }
  if (frameworks.runtime) lines.push(`Runtime: ${frameworks.runtime}`);
  if (scripts.packageManager) lines.push(`Package manager: ${scripts.packageManager}`);
  lines.push('');

  // Commands — the most actionable info for an LLM assistant
  if (scripts.commands.length > 0) {
    lines.push('## Commands');
    const key = ['dev', 'build', 'test', 'lint'] as const;
    for (const kind of key) {
      const cmd = scripts.commands.find((c) => c.kind === kind);
      if (cmd) lines.push(`- **${kind}:** \`${cmd.command}\``);
    }
    const others = scripts.commands.filter((c) => !key.includes(c.kind as never));
    for (const cmd of others.slice(0, 3)) {
      lines.push(`- \`${cmd.command}\` — ${cmd.description}`);
    }
    lines.push('');
  }

  // Entry points
  const allFiles = [
    ...entryPoints.map((e) => ({ path: e.relativePath, desc: e.description })),
    ...startHere
      .filter((s) => !entryPoints.some((e) => e.relativePath === s.relativePath))
      .map((s) => ({ path: s.relativePath, desc: s.reason })),
  ].slice(0, 6);

  if (allFiles.length > 0) {
    lines.push('## Key Files');
    for (const f of allFiles) {
      lines.push(`- \`${f.path}\` — ${f.desc}`);
    }
    lines.push('');
  }

  // Architecture hint
  const secondary = frameworks.secondary
    .filter((f) => !['linting', 'build_tool'].includes(f.category))
    .map((f) => f.name);
  if (secondary.length > 0) {
    lines.push('## Libraries');
    lines.push(secondary.join(', '));
    lines.push('');
  }

  // Test strategy
  const testFrameworks = frameworks.all.filter((f) => f.category === 'testing').map((f) => f.name);
  if (testFrameworks.length > 0 || tools.hasTests) {
    lines.push('## Testing');
    lines.push(
      testFrameworks.length > 0
        ? `Uses ${testFrameworks.join(', ')}.${tools.testDirHint ? ` Tests in \`${tools.testDirHint}\`.` : ''}`
        : `Test directory: \`${tools.testDirHint ?? 'found'}\``,
    );
    lines.push('');
  }

  // Infrastructure
  const infra: string[] = [];
  if (tools.ci) infra.push(tools.ciWorkflowCount > 0 ? `${tools.ci} (${tools.ciWorkflowCount} workflows)` : tools.ci);
  if (tools.container.length > 0) infra.push(tools.container.join(', '));
  if (infra.length > 0) {
    lines.push('## Infrastructure');
    lines.push(infra.join('  ·  '));
    lines.push('');
  }

  // Language summary (brief)
  const codeLangs = languages.filter((l) => !CONFIG_LANGUAGES.has(l.name)).slice(0, 4);
  if (codeLangs.length > 0) {
    lines.push('## Codebase');
    lines.push(
      codeLangs
        .map((l) => `${l.name} ${l.percentage}%`)
        .join('  ·  '),
    );
    lines.push(`${result.totalFiles} files  ·  ${result.totalLines.toLocaleString('en-US')} lines`);
    lines.push('');
  }

  // Git context
  if (git.isRepo && git.lastCommit) {
    lines.push('## Recent Activity');
    lines.push(`Branch: \`${git.branch ?? 'main'}\`  ·  Last commit ${
      git.lastCommit.daysAgo === 0 ? 'today' : `${git.lastCommit.daysAgo}d ago`
    } by ${git.lastCommit.author}`);
    if (git.recentCommits > 0) {
      lines.push(`${git.recentCommits} commits  ·  ${git.recentContributors} contributors  (30 days)`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*This brief was generated by codeglance from file structure and manifest analysis.*');
  lines.push('*It is a starting point, not a complete description of the codebase.*');

  return lines.join('\n');
}
