import type { AnalysisResult } from '../analyzer.js';
import { CONFIG_LANGUAGES } from '../detectors/languages.js';

function formatNum(n: number): string {
  return n.toLocaleString('en-US');
}

function formatAge(days: number): string {
  if (days < 1)   return 'today';
  if (days === 1) return '1 day ago';
  if (days < 30)  return `${days} days ago`;
  if (days < 365) return `${Math.round(days / 30)} months ago`;
  const y = Math.round(days / 365);
  return `${y} year${y > 1 ? 's' : ''} ago`;
}

export function renderMarkdown(result: AnalysisResult): string {
  const { name, frameworks, scripts, entryPoints, startHere, languages, tools, git } = result;
  const generated = new Date().toISOString().split('T')[0];

  const lines: string[] = [];

  lines.push(`# Codebase Tour: ${name}`);
  lines.push('');
  lines.push(`> Generated by [codeglance](https://github.com/username/codeglance) on ${generated}.`);
  lines.push('> This file is heuristic-based, not exhaustive.');
  lines.push('');

  // What is this
  lines.push('## What Is This?');
  lines.push('');
  if (frameworks.summary !== 'Unknown project type') {
    lines.push(`**${frameworks.summary}**`);
    lines.push('');
  }
  if (frameworks.runtime) {
    lines.push(`- **Runtime:** ${frameworks.runtime}`);
  }
  if (scripts.packageManager) {
    lines.push(`- **Package manager:** ${scripts.packageManager}`);
  }
  if (frameworks.primary.length > 0) {
    const p = frameworks.primary.map((f) => f.name + (f.version ? ` ${f.version}` : '')).join(', ');
    lines.push(`- **Primary frameworks:** ${p}`);
  }
  const secondary = frameworks.secondary
    .filter((f) => !['linting', 'build_tool'].includes(f.category))
    .map((f) => f.name)
    .slice(0, 6);
  if (secondary.length > 0) {
    lines.push(`- **Key libraries:** ${secondary.join(', ')}`);
  }
  lines.push('');

  // How to run it
  if (scripts.commands.length > 0) {
    lines.push('## How to Run It');
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    for (const cmd of scripts.commands) {
      lines.push(`| \`${cmd.command}\` | ${cmd.description} |`);
    }
    lines.push('');
  }

  // Where to start
  const allFiles = [
    ...entryPoints.map((e) => ({ path: e.relativePath, desc: e.description })),
    ...startHere
      .filter((s) => !entryPoints.some((e) => e.relativePath === s.relativePath))
      .map((s) => ({ path: s.relativePath, desc: s.reason })),
  ].slice(0, 8);

  if (allFiles.length > 0) {
    lines.push('## Where to Start');
    lines.push('');
    lines.push('Files to open first (heuristic ranking):');
    lines.push('');
    for (const f of allFiles) {
      lines.push(`- \`${f.path}\` — ${f.desc}`);
    }
    lines.push('');
  }

  // Tools
  lines.push('## Tools & Infrastructure');
  lines.push('');
  const testFrameworks = frameworks.all.filter((f) => f.category === 'testing').map((f) => f.name);
  if (testFrameworks.length > 0 || tools.hasTests) {
    lines.push(`- **Testing:** ${testFrameworks.join(', ') || 'found'}`);
  }
  if (tools.ci) {
    const wf = tools.ciWorkflowCount > 0 ? ` (${tools.ciWorkflowCount} workflows)` : '';
    lines.push(`- **CI/CD:** ${tools.ci}${wf}`);
  }
  if (tools.container.length > 0) {
    lines.push(`- **Container:** ${tools.container.join(', ')}`);
  }
  if (tools.linting.length > 0) {
    lines.push(`- **Linting:** ${tools.linting.join(', ')}`);
  }
  if (tools.hasEnvFile) {
    lines.push(`- **Env files:** ${tools.envFiles.join(', ')}`);
  }
  lines.push('');

  // Languages
  const codeLangs = languages.filter((l) => !CONFIG_LANGUAGES.has(l.name)).slice(0, 8);
  if (codeLangs.length > 0) {
    lines.push('## Language Breakdown');
    lines.push('');
    lines.push('| Language | Files | Lines | Share |');
    lines.push('|----------|------:|------:|------:|');
    for (const lang of codeLangs) {
      lines.push(`| ${lang.name} | ${formatNum(lang.files)} | ${formatNum(lang.lines)} | ${lang.percentage}% |`);
    }
    lines.push('');
  }

  // Git
  if (git.isRepo) {
    lines.push('## Git Activity');
    lines.push('');
    if (git.branch) lines.push(`- **Branch:** \`${git.branch}\``);
    if (git.lastCommit) {
      lines.push(`- **Last commit:** ${formatAge(git.lastCommit.daysAgo)} — "${git.lastCommit.shortMessage}" (${git.lastCommit.author})`);
    }
    if (git.recentCommits > 0) {
      lines.push(`- **Last 30 days:** ${git.recentCommits} commits by ${git.recentContributors} contributors`);
    }
    if (git.repoAgeDays !== null) {
      lines.push(`- **Repo age:** ${formatAge(git.repoAgeDays)}`);
    }
    lines.push('');
  }

  // Health
  const healthItems: Array<[boolean, string]> = [
    [tools.hasTests,      'Tests'],
    [tools.ci !== null,   'CI/CD'],
    [tools.hasReadme,     'README'],
    [tools.hasLicense,    'License'],
    [tools.hasChangelog,  'Changelog'],
    [tools.hasContributing, 'Contributing guide'],
  ];
  lines.push('## Project Health');
  lines.push('');
  for (const [ok, label] of healthItems) {
    lines.push(`- ${ok ? '✅' : '⬜'} ${label}`);
  }
  lines.push('');
  lines.push(`*${formatNum(result.totalFiles)} files · ${formatNum(result.totalLines)} lines · analyzed in ${result.durationMs}ms*`);

  return lines.join('\n');
}
